### ISSUE TITLE
BC breaks with Symfony 2.8 & GTM bundle 2.4

### ISSUE THREAD

**Issue by JunkMyFunk** [xyNNN/GoogleTagManagerBundle#30]
Running Symfony 2.8.27, updated to xyNNN/GoogleTagManagerBundle 2.4, received the error:

```
[InvalidArgumentException]
  The service "listener.google_tag_manager" must be public as event listeners are lazy-loaded.
```

when booting the application (even post-update cache:clear hook wouldn't complete). Rolled back to 2.3 and all is ok.

**Comment by xyNNN** [comment]
We fixed this in the new release 2.4.1 (see https://github.com/xyNNN/GoogleTagManagerBundle/releases/tag/2.4.1). Please update to the latest version.

Thank you for reporting!
