### ISSUE TITLE
Support for multiple environments

### ISSUE THREAD

**Issue by chrs-myrs** [xyNNN/GoogleTagManagerBundle#41]
It's a great extension, but missing one key thing that we need, the support for multiple tag manager environments.  I'd like to allign these with our test/staging environments.

Essentially these environments are signalled by adding some parameters to the URLs in both the header and footer.  I wonder if we could set these somehow in the config so that they can be passed from environment variables.

&gtm_auth=<auth-code>&gtm_preview=env-33&gtm_cookies_win=x

Perhaps just a section for additional URL parameters so that it isn't tied to the current implementation?

**Comment by chrs-myrs** [comment]
https://github.com/xyNNN/GoogleTagManagerBundle/pull/42/files

**Comment by xyNNN** [comment]
Thank you very much for your pull request! I will give you ASAP feedback.

**Comment by xyNNN** [comment]
Fixed by https://github.com/xyNNN/GoogleTagManagerBundle/releases/tag/3.1.0
