### ISSUE TITLE
Support Symfony 6

### ISSUE THREAD

**Issue by hcerveragarc** [xyNNN/GoogleTagManagerBundle#46]
Hello there,

I was wondering if it would be possible to check that dependencies symfony/* version 6 are compatible with this package and, if so, upgrade the composer to allow them.

At least with symfony/dependency-injection, it doesn't seem that any breaking change has been added - https://github.com/symfony/dependency-injection/releases/tag/v6.0.0

Thanks already for your project.

**Comment by xyNNN** [comment]
Currently I'm busy and not able to answer your question. Perhaps you can fork this repository and try out if this package works smooth with the all components of the newest major release? Feel free to create a pull request! Thanks!

**Comment by hcerveragarc** [comment]
Thanks for your answer. We are currently upgrading a project to Symfony 6 and your package is a mandatory dependency. I will create a fork next time I have this project in my hands.

**Comment by dsbe-ak** [comment]
I've created a pull request #47

**Comment by hcerveragarc** [comment]
@dsbe-ak Thanks :)

**Comment by xyNNN** [comment]
See https://github.com/xyNNN/GoogleTagManagerBundle/releases/tag/4.0.0
