### ISSUE TITLE
Release 3.1.2 contains breaking changes

### ISSUE THREAD

**Issue by zarunet** [xyNNN/GoogleTagManagerBundle#51]
Following the merge of #49, it looks like release 3.1.2 was tagged directly on master, thus including in that release every change made for 4.x

I'm unable to open a PR to fix this, as it involves creating a new branch :
```
git checkout tags/3.1.1 -b 3.x
git cherry-pick f477eee
```

...then tagging _that_ as 3.1.x

Is this acceptable to you?

**Comment by xyNNN** [comment]
Oops, you're right - my fault!
I've fix it in the new release 3.1.3 
https://github.com/xyNNN/GoogleTagManagerBundle/releases/tag/3.1.3
